ID_PLAYER = 0
ID_CREATURE = 1
ID_ACTION_PLAY_LAND = 2
ID_ACTION_TAP_FOR_MANA = 3
ID_ACTION_CAST_SPELL = 4
ID_ACTION_PASS_TURN = 5
ID_PHASE_BEGINNING = 10
ID_PHASE_MAIN1 = 11
ID_PHASE_COMBAT = 12
ID_PHASE_MAIN2 = 13
ID_PHASE_ENDING = 14
ID_STEP_UNTAP = 20
ID_STEP_DRAW = 21
ID_STEP_PRE_COMBAT_MAIN = 22
ID_STEP_BEGINNING_OF_COMBAT = 23
ID_STEP_DECLARE_ATTACKERS = 24
ID_STEP_DECLARE_BLOCKERS = 25
ID_STEP_COMBAT_DAMAGE = 26
ID_STEP_END_OF_COMBAT = 27
ID_STEP_POST_COMBAT_MAIN = 28
ID_STEP_END_OF_TURN = 29
ID_ZONE_HAND = 100
ID_ZONE_BATTLEFIELD = 101
ID_ZONE_LIBRARY = 102
ID_ZONE_GRAVEYARD = 103
ID_ZONE_STACK = 104
ID_ZONE_EXILE = 105
ID_REL_CONTROLS = 200
ID_REL_IS_IN_ZONE = 201
ID_REL_HAS_ABILITY = 202
ID_REL_TAPPED = 203
ID_REL_IS_BLOCKING = 204
ID_MANA_GREEN = 300
ID_MANA_BLUE = 301
ID_MANA_BLACK = 302
ID_MANA_RED = 303
ID_MANA_WHITE = 304
ID_MANA_COLORLESS = 305
ID_MANA_GENERIC = 306 # Represents generic mana cost
ID_CARD_FOREST = 1000
ID_CARD_ISLAND = 1001
ID_CARD_MOUNTAIN = 1002
ID_CARD_SWAMP = 1003
ID_CARD_PLAINS = 1004
ID_CARD_CUSTOM_START = 6000 # Starting ID for dynamically loaded cards
ID_CARD_GRIZZLY_BEARS = 2000
ID_CARD_GIANT_STRENGTH = 2001
ID_ABILITY_HASTE = 5000
ID_ABILITY_TRAMPLE = 5001
ID_ABILITY_FLYING = 5002
ID_ABILITY_FIRST_STRIKE = 5003
ID_ABILITY_DEATHTOUCH = 5004
ID_ABILITY_LIFELINK = 5005
ID_ABILITY_PROTECTION = 5006
ID_ABILITY_DOUBLE_STRIKE = 5007
ID_ABILITY_VIGILANCE = 5008
ID_ABILITY_INDESTRUCTIBLE = 5009
ID_ABILITY_FLASH = 5010
ID_ABILITY_HEXPROOF = 5011
ID_ABILITY_PROWESS = 5012
ID_ABILITY_MENACE = 5013
ID_ABILITY_DEFENDER = 5014
ID_ABILITY_REACH = 5015
ID_ABILITY_TAP_ADD_GREEN = 5100
ID_ABILITY_TAP_ADD_BLUE = 5101
ID_ABILITY_TAP_ADD_BLACK = 5102
ID_ABILITY_TAP_ADD_RED = 5103
ID_ABILITY_TAP_ADD_WHITE = 5104
ID_CARD_ADHERENT_OF_HOPE = 5105
ID_CARD_ALCHEMISTS_GIFT = 5106
ID_CARD_ALPINE_HOUNDMASTER = 5107
ID_CARD_ALPINE_WATCHDOG = 5108
ID_CARD_ANGELIC_ASCENSION = 5109
ID_CARD_ANIMAL_SANCTUARY = 5110
ID_CARD_ANOINTED_CHORISTER = 5111
ID_CARD_ARCHFIENDS_VESSEL = 5112
ID_CARD_AVEN_GAGGLEMASTER = 5113
ID_CARD_BAD_DEAL = 5115
ID_CARD_BANESLAYER_ANGEL = 5116
ID_CARD_BASRI_KET = 5118
ID_CARD_BASRIS_ACOLYTE = 5119
ID_CARD_BASRIS_AEGIS = 5120
ID_CARD_BASRIS_LIEUTENANT = 5121
ID_CARD_BASRIS_SOLIDARITY = 5122
ID_CARD_BATTLE_RATTLE_SHAMAN = 5124
ID_CARD_BLOOD_GLUTTON = 5125
ID_CARD_BLOODFELL_CAVES = 5126
ID_CARD_BLOSSOMING_SANDS = 5127
ID_CARD_BOLT_HOUND = 5128
ID_CARD_BONE_PIT_BRUTE = 5129
ID_CARD_BRASH_TAUNTER = 5130
ID_CARD_BURLFIST_OAK = 5131
ID_CARD_BURN_BRIGHT = 5132
ID_CARD_CAGED_ZOMBIE = 5133
ID_CARD_CANCEL = 5134
ID_CARD_CANOPY_STALKER = 5135
ID_CARD_CAPTURE_SPHERE = 5136
ID_CARD_CARRION_GRUB = 5137
ID_CARD_CELESTIAL_ENFORCER = 5138
ID_CARD_CHANDRAS_FIREMAW = 5139
ID_CARD_CHANDRAS_INCINERATOR = 5140
ID_CARD_CHANDRAS_MAGMUTT = 5141
ID_CARD_CHANDRAS_PYRELING = 5142
ID_CARD_CHROMATIC_ORRERY = 5145
ID_CARD_CHROME_REPLICATOR = 5146
ID_CARD_COLOSSAL_DREADMAW = 5147
ID_CARD_CONCLAVE_MENTOR = 5148
ID_CARD_CONCORDIA_PEGASUS = 5149
ID_CARD_CONSPICUOUS_SNOOP = 5150
ID_CARD_CONTAINMENT_PRIEST = 5151
ID_CARD_CRASH_THROUGH = 5152
ID_CARD_CRYPT_LURKER = 5153
ID_CARD_CULTIVATE = 5154
ID_CARD_DAYBREAK_CHARGER = 5155
ID_CARD_DEATHBLOOM_THALLID = 5156
ID_CARD_DEFIANT_STRIKE = 5157
ID_CARD_DEMONIC_EMBRACE = 5158
ID_CARD_DESTRUCTIVE_TAMPERING = 5159
ID_CARD_DIRE_FLEET_WARMONGER = 5160
ID_CARD_DISCONTINUITY = 5161
ID_CARD_DISMAL_BACKWATER = 5162
ID_CARD_DOUBLE_VISION = 5163
ID_CARD_DROWSING_TYRANNODON = 5164
ID_CARD_DUB = 5165
ID_CARD_DURESS = 5166
ID_CARD_ELDER_GARGAROTH = 5167
ID_CARD_ELIMINATE = 5168
ID_CARD_ENTHRALLING_HOLD = 5169
ID_CARD_EPITAPH_GOLEM = 5170
ID_CARD_EXPERIMENTAL_OVERLOAD = 5171
ID_CARD_FABLED_PASSAGE = 5172
ID_CARD_FAITHS_FETTERS = 5173
ID_CARD_FALCONER_ADEPT = 5174
ID_CARD_FEAT_OF_RESISTANCE = 5175
ID_CARD_FELINE_SOVEREIGN = 5176
ID_CARD_FETID_IMP = 5177
ID_CARD_FIERCE_EMPATH = 5178
ID_CARD_FIERY_EMANCIPATION = 5179
ID_CARD_FINISHING_BLOW = 5180
ID_CARD_FORGOTTEN_SENTINEL = 5181
ID_CARD_FRANTIC_INVENTORY = 5182
ID_CARD_FROST_BREATH = 5183
ID_CARD_FUNGAL_REBIRTH = 5184
ID_CARD_FURIOUS_RISE = 5185
ID_CARD_FUROR_OF_THE_BITTEN = 5186
ID_CARD_GALE_SWOOPER = 5188
ID_CARD_GARRUKS_GOREHORN = 5189
ID_CARD_GARRUKS_HARBINGER = 5190
ID_CARD_GARRUKS_UPRISING = 5191
ID_CARD_GARRUKS_WARSTEED = 5192
ID_CARD_GHOSTLY_PILFERER = 5195
ID_CARD_GLOOM_SOWER = 5196
ID_CARD_GLORIOUS_ANTHEM = 5197
ID_CARD_GNARLED_SAGE = 5198
ID_CARD_GOBLIN_ARSONIST = 5199
ID_ABILITY_GRANT_P_T = 5200
ID_CARD_GOBLIN_WIZARDRY = 5200
ID_CARD_GOREMAND = 5201
ID_CARD_GRASP_OF_DARKNESS = 5202
ID_CARD_GRIFFIN_AERIE = 5203
ID_CARD_GRIM_TUTOR = 5204
ID_CARD_HAVOC_JESTER = 5205
ID_CARD_HEARTFIRE_IMMOLATOR = 5206
ID_CARD_HELLKITE_PUNISHER = 5207
ID_CARD_HEROIC_INTERVENTION = 5208
ID_CARD_HISTORIAN_OF_ZHALFIR = 5209
ID_CARD_HOBBLEFIEND = 5210
ID_CARD_HOODED_BLIGHTFANG = 5211
ID_CARD_HUNTERS_EDGE = 5212
ID_CARD_IDOL_OF_ENDURANCE = 5213
ID_CARD_IGNEOUS_CUR = 5214
ID_CARD_INDULGING_PATRICIAN = 5215
ID_CARD_INFERNAL_SCARRING = 5216
ID_CARD_INVIGORATING_SURGE = 5217
ID_CARD_JESKAI_ELDER = 5218
ID_CARD_JUNGLE_HOLLOW = 5220
ID_CARD_KEEN_GLIDEMASTER = 5222
ID_CARD_KERAL_KEEP_DISCIPLES = 5223
ID_CARD_KINETIC_AUGUR = 5224
ID_CARD_KITESAIL_FREEBOOTER = 5225
ID_CARD_LEAFKIN_AVENGER = 5226
ID_CARD_LEGIONS_JUDGMENT = 5227
ID_CARD_LIBRARY_LARCENIST = 5228
ID_CARD_LIFE_GOES_ON = 5229
ID_CARD_LIGHT_OF_PROMISE = 5230
ID_CARD_LILIANAS_DEVOTEE = 5231
ID_CARD_LILIANAS_SCORN = 5232
ID_CARD_LILIANAS_SCROUNGER = 5233
ID_CARD_LILIANAS_STANDARD_BEARER = 5234
ID_CARD_LILIANAS_STEWARD = 5235
ID_CARD_LLANOWAR_VISIONARY = 5238
ID_CARD_LOFTY_DENIAL = 5239
ID_CARD_LORESCALE_COATL = 5240
ID_CARD_MAKESHIFT_BATTALION = 5241
ID_CARD_MALEFIC_SCYTHE = 5242
ID_CARD_MASKED_BLACKGUARD = 5244
ID_CARD_MASSACRE_WURM = 5245
ID_CARD_MAZEMIND_TOME = 5246
ID_CARD_METEORITE = 5247
ID_CARD_MIND_ROT = 5248
ID_CARD_MISCAST = 5249
ID_CARD_MISTRAL_SINGER = 5250
ID_CARD_MYSTIC_SKYFISH = 5251
ID_CARD_NECROMENTIA = 5252
ID_CARD_NINE_LIVES = 5254
ID_CARD_OBSESSIVE_STITCHER = 5255
ID_CARD_ONAKKE_OGRE = 5256
ID_CARD_OPT = 5257
ID_CARD_ORNERY_DILOPHOSAUR = 5258
ID_CARD_PACK_LEADER = 5259
ID_CARD_PALLADIUM_MYR = 5260
ID_CARD_PEER_INTO_THE_ABYSS = 5261
ID_CARD_PESTILENT_HAZE = 5262
ID_CARD_PITCHBURN_DEVILS = 5263
ID_CARD_PORTCULLIS_VINE = 5264
ID_CARD_PREDATORY_WURM = 5265
ID_CARD_PRIDEMALKIN = 5266
ID_CARD_PRIMAL_MIGHT = 5267
ID_CARD_PRISMITE = 5268
ID_CARD_PURSUED_WHALE = 5269
ID_CARD_QUIRION_DRYAD = 5270
ID_CARD_RADIANT_FOUNTAIN = 5272
ID_CARD_RAIN_OF_REVELATION = 5273
ID_CARD_RAMBUNCTIOUS_MUTT = 5274
ID_CARD_RANGERS_GUILE = 5275
ID_CARD_READ_THE_TIDES = 5276
ID_CARD_RETURN_TO_NATURE = 5277
ID_CARD_REVITALIZE = 5278
ID_CARD_REWIND = 5279
ID_CARD_RIDDLEFORM = 5280
ID_CARD_RISE_AGAIN = 5282
ID_CARD_ROAMING_GHOSTLIGHT = 5283
ID_CARD_ROOKIE_MISTAKE = 5284
ID_CARD_ROUSING_READ = 5285
ID_CARD_RUGGED_HIGHLANDS = 5286
ID_CARD_RUN_AFOUL = 5287
ID_CARD_RUNED_HALO = 5288
ID_CARD_SABERTOOTH_MAULER = 5289
ID_CARD_SANCTUM_OF_ALL = 5290
ID_CARD_SANCTUM_OF_CALM_WATERS = 5291
ID_CARD_SANCTUM_OF_FRUITFUL_HARVEST = 5292
ID_CARD_SANCTUM_OF_SHATTERED_HEIGHTS = 5293
ID_CARD_SANCTUM_OF_STONE_FANGS = 5294
ID_CARD_SANCTUM_OF_TRANQUIL_LIGHT = 5295
ID_CARD_SANGUINE_INDULGENCE = 5296
ID_CARD_SCAVENGING_OOZE = 5297
ID_CARD_SCORCHING_DRAGONFIRE = 5298
ID_CARD_SCOURED_BARRENS = 5299
ID_CARD_SEASONED_HALLOWBLADE = 5300
ID_CARD_SECURE_THE_SCENE = 5301
ID_CARD_SEE_THE_TRUTH = 5302
ID_CARD_SELFLESS_SAVIOR = 5303
ID_CARD_SETESSAN_TRAINING = 5304
ID_CARD_SHACKLEGEIST = 5305
ID_CARD_SHIPWRECK_DOWSER = 5306
ID_CARD_SHOCK = 5307
ID_CARD_SHORT_SWORD = 5308
ID_CARD_SIEGE_STRIKER = 5309
ID_CARD_SIGILED_CONTENDER = 5310
ID_CARD_SILENT_DART = 5311
ID_CARD_SILVERSMOTE_GHOUL = 5312
ID_CARD_SKELETON_ARCHER = 5313
ID_CARD_SKYSCANNER = 5314
ID_CARD_SKYWAY_SNIPER = 5315
ID_CARD_SNARESPINNER = 5316
ID_CARD_SOLEMN_SIMULACRUM = 5317
ID_CARD_SOUL_SEAR = 5318
ID_CARD_SPARKHUNTER_MASTICORE = 5319
ID_CARD_SPEAKER_OF_THE_HEAVENS = 5320
ID_CARD_SPELLGORGER_WEIRD = 5321
ID_CARD_SPINED_MEGALODON = 5322
ID_CARD_SPIRIT_OF_MALEVOLENCE = 5323
ID_CARD_SPOREWEB_WEAVER = 5324
ID_CARD_STAUNCH_SHIELDMATE = 5325
ID_CARD_STORM_CALLER = 5326
ID_CARD_STORMWING_ENTITY = 5327
ID_CARD_SUBLIME_EPIPHANY = 5329
ID_CARD_SURE_STRIKE = 5330
ID_CARD_SWIFT_RESPONSE = 5331
ID_CARD_SWIFTWATER_CLIFFS = 5332
ID_CARD_TAVERN_SWINDLER = 5333
ID_CARD_TEFERIS_AGELESS_INSIGHT = 5334
ID_CARD_TEFERIS_PROTEGE = 5335
ID_CARD_TEFERIS_TUTELAGE = 5336
ID_CARD_TEFERIS_WAVECASTER = 5337
ID_CARD_TEMPERED_VETERAN = 5340
ID_CARD_TEMPLE_OF_EPIPHANY = 5341
ID_CARD_TEMPLE_OF_MALADY = 5342
ID_CARD_TEMPLE_OF_MYSTERY = 5343
ID_CARD_TEMPLE_OF_SILENCE = 5344
ID_CARD_TEMPLE_OF_TRIUMPH = 5345
ID_CARD_TERROR_OF_THE_PEAKS = 5346
ID_CARD_THIEVES_GUILD_ENFORCER = 5347
ID_CARD_THORNWOOD_FALLS = 5348
ID_CARD_THRASHING_BRONTODON = 5349
ID_CARD_THRILL_OF_POSSIBILITY = 5350
ID_CARD_TIDE_SKIMMER = 5351
ID_CARD_TITANIC_GROWTH = 5352
ID_CARD_TOLARIAN_KRAKEN = 5353
ID_CARD_TOME_ANIMA = 5354
ID_CARD_TORMODS_CRYPT = 5355
ID_CARD_TRACK_DOWN = 5356
ID_CARD_TRAITOROUS_GREED = 5357
ID_CARD_TRANQUIL_COVE = 5358
ID_CARD_TRANSMOGRIFY = 5359
ID_CARD_TRUFFLESNOUT = 5360
ID_CARD_TURN_TO_SLAG = 5361
ID_CARD_TURRET_OGRE = 5362
ID_CARD_TWINBLADE_ASSASSINS = 5363
ID_CARD_UNLEASH_FURY = 5365
ID_CARD_UNSUBSTANTIATE = 5366
ID_CARD_VALOROUS_STEED = 5367
ID_CARD_VILLAGE_RITES = 5368
ID_CARD_VODALIAN_ARCANIST = 5370
ID_CARD_VOLCANIC_GEYSER = 5371
ID_CARD_VOLCANIC_SALVO = 5372
ID_CARD_VRYN_WINGMARE = 5373
ID_CARD_WAKER_OF_WAVES = 5374
ID_CARD_WALKING_CORPSE = 5375
ID_CARD_WALL_OF_RUNES = 5376
ID_CARD_WARDED_BATTLEMENTS = 5377
ID_CARD_WARDEN_OF_THE_WOODS = 5378
ID_CARD_WATCHER_OF_THE_SPHERES = 5379
ID_CARD_WILDWOOD_PATROL = 5380
ID_CARD_WILDWOOD_SCOURGE = 5381
ID_CARD_WIND_SCARRED_CRAG = 5382
ID_CARD_WISHCOIN_CRAB = 5383
ID_CARD_WITCHS_CAULDRON = 5384
ID_CARD_AZUSA_LOST_BUT_SEEKING = 5385
ID_CARD_BARRIN_TOLARIAN_ARCHMAGE = 5386
ID_CARD_BASRI_DEVOTED_PALADIN = 5387
ID_CARD_CHANDRA_FLAMES_CATALYST = 5388
ID_CARD_CHANDRA_HEART_OF_FIRE = 5389
ID_CARD_GADRAK_THE_CROWN_SCOURGE = 5390
ID_CARD_GARRUK_SAVAGE_HERALD = 5391
ID_CARD_GARRUK_UNLEASHED = 5392
ID_CARD_JOLRAEL_MWONVULI_RECLUSE = 5393
ID_CARD_KAERVEK_THE_SPITEFUL = 5394
ID_CARD_LILIANA_DEATH_MAGE = 5395
ID_CARD_LILIANA_WAKER_OF_THE_DEAD = 5396
ID_CARD_MANGARA_THE_DIPLOMAT = 5397
ID_CARD_NIAMBI_ESTEEMED_SPEAKER = 5398
ID_CARD_RADHA_HEART_OF_KELD = 5399
ID_CARD_RIN_AND_SERI_INSEPARABLE = 5400
ID_CARD_SUBIRA_TULZIDI_CARAVANNER = 5401
ID_CARD_TEFERI_MASTER_OF_TIME = 5402
ID_CARD_TEFERI_TIMELESS_VOYAGER = 5403
ID_CARD_UGIN_THE_SPIRIT_DRAGON = 5404
ID_CARD_VITO_THORN_OF_THE_DUSK_ROSE = 5405

ID_TO_NAME = {
    ID_PLAYER: "Player",
    ID_CREATURE: "Creature",
    ID_ACTION_PLAY_LAND: "Play Land Action",
    ID_ACTION_TAP_FOR_MANA: "Tap for Mana Action",
    ID_ACTION_CAST_SPELL: "Cast Spell Action",
    ID_ACTION_PASS_TURN: "Pass Turn Action",

    ID_PHASE_BEGINNING: "Beginning Phase",
    ID_PHASE_MAIN1: "Pre-Combat Main Phase",
    ID_PHASE_COMBAT: "Combat Phase",
    ID_PHASE_MAIN2: "Post-Combat Main Phase",
    ID_PHASE_ENDING: "Ending Phase",

    ID_STEP_UNTAP: "Untap Step",
    ID_STEP_UPKEEP: "Upkeep Step",
    ID_STEP_DRAW: "Draw Step",
    ID_STEP_PRE_COMBAT_MAIN: "Pre-Combat Main Step",
    ID_STEP_BEGINNING_OF_COMBAT: "Beginning of Combat Step",
    ID_STEP_DECLARE_ATTACKERS: "Declare Attackers Step",
    ID_STEP_DECLARE_BLOCKERS: "Declare Blockers Step",
    ID_STEP_COMBAT_DAMAGE: "Combat Damage Step",
    ID_STEP_END_OF_COMBAT: "End of Combat Step",
    ID_STEP_POST_COMBAT_MAIN: "Post-Combat Main Step",
    ID_STEP_END: "End Step",
    ID_STEP_CLEANUP: "Cleanup Step",

    ID_ZONE_HAND: "Hand",
    ID_ZONE_BATTLEFIELD: "Battlefield",
    ID_ZONE_LIBRARY: "Library",
    ID_ZONE_GRAVEYARD: "Graveyard",
    ID_ZONE_STACK: "Stack",
    ID_ZONE_EXILE: "Exile",

    ID_REL_CONTROLS: "Controls",
    ID_REL_IS_IN_ZONE: "Is In Zone",
    ID_REL_HAS_ABILITY: "Has Ability",
    ID_REL_TAPPED: "Tapped",
    ID_REL_IS_BLOCKING: "Is Blocking",

    ID_MANA_GREEN: "Green Mana",
    ID_MANA_BLUE: "Blue Mana",
    ID_MANA_BLACK: "Black Mana",
    ID_MANA_RED: "Red Mana",
    ID_MANA_WHITE: "White Mana",
    ID_MANA_COLORLESS: "Colorless Mana",
    ID_MANA_GENERIC: "Generic Mana",

    ID_CARD_FOREST: "Forest",
    ID_CARD_ISLAND: "Island",
    ID_CARD_MOUNTAIN: "Mountain",
    ID_CARD_SWAMP: "Swamp",
    ID_CARD_PLAINS: "Plains",
    ID_CARD_GRIZZLY_BEARS: "Grizzly Bears",
    ID_CARD_GIANT_STRENGTH: "Giant Strength",

    ID_ABILITY_HASTE: "Haste",
    ID_ABILITY_TRAMPLE: "Trample",
    ID_ABILITY_FLYING: "Flying",
    ID_ABILITY_FIRST_STRIKE: "First Strike",
    ID_ABILITY_DEATHTOUCH: "Deathtouch",
    ID_ABILITY_LIFELINK: "Lifelink",
    ID_ABILITY_PROTECTION: "Protection",
    ID_ABILITY_DOUBLE_STRIKE: "Double Strike",
    ID_ABILITY_VIGILANCE: "Vigilance",
    ID_ABILITY_INDESTRUCTIBLE: "Indestructible",
    ID_ABILITY_FLASH: "Flash",
    ID_ABILITY_HEXPROOF: "Hexproof",
    ID_ABILITY_PROWESS: "Prowess",
    ID_ABILITY_MENACE: "Menace",
    ID_ABILITY_DEFENDER: "Defender",
    ID_ABILITY_REACH: "Reach",
    ID_ABILITY_TAP_ADD_GREEN: "Tap: Add Green Mana",
    ID_ABILITY_TAP_ADD_BLUE: "Tap: Add Blue Mana",
    ID_ABILITY_TAP_ADD_BLACK: "Tap: Add Black Mana",
    ID_ABILITY_TAP_ADD_RED: "Tap: Add Red Mana",
    ID_ABILITY_TAP_ADD_WHITE: "Tap: Add White Mana",
}

ID_TO_NAME = {
    ID_PLAYER: "Player",
    ID_CREATURE: "Creature",
    ID_ACTION_PLAY_LAND: "Play Land Action",
    ID_ACTION_TAP_FOR_MANA: "Tap for Mana Action",
    ID_ACTION_CAST_SPELL: "Cast Spell Action",
    ID_ACTION_PASS_TURN: "Pass Turn Action",

    ID_PHASE_BEGINNING: "Beginning Phase",
    ID_PHASE_MAIN1: "Pre-Combat Main Phase",
    ID_PHASE_COMBAT: "Combat Phase",
    ID_PHASE_MAIN2: "Post-Combat Main Phase",
    ID_PHASE_ENDING: "Ending Phase",

    ID_STEP_UNTAP: "Untap Step",
    ID_STEP_UPKEEP: "Upkeep Step",
    ID_STEP_DRAW: "Draw Step",
    ID_STEP_PRE_COMBAT_MAIN: "Pre-Combat Main Step",
    ID_STEP_BEGINNING_OF_COMBAT: "Beginning of Combat Step",
    ID_STEP_DECLARE_ATTACKERS: "Declare Attackers Step",
    ID_STEP_DECLARE_BLOCKERS: "Declare Blockers Step",
    ID_STEP_COMBAT_DAMAGE: "Combat Damage Step",
    ID_STEP_END_OF_COMBAT: "End of Combat Step",
    ID_STEP_POST_COMBAT_MAIN: "Post-Combat Main Step",
    ID_STEP_END: "End Step",
    ID_STEP_CLEANUP: "Cleanup Step",

    ID_ZONE_HAND: "Hand",
    ID_ZONE_BATTLEFIELD: "Battlefield",
    ID_ZONE_LIBRARY: "Library",
    ID_ZONE_GRAVEYARD: "Graveyard",
    ID_ZONE_STACK: "Stack",
    ID_ZONE_EXILE: "Exile",

    ID_REL_CONTROLS: "Controls",
    ID_REL_IS_IN_ZONE: "Is In Zone",
    ID_REL_HAS_ABILITY: "Has Ability",
    ID_REL_TAPPED: "Tapped",
    ID_REL_IS_BLOCKING: "Is Blocking",

    ID_MANA_GREEN: "Green Mana",
    ID_MANA_BLUE: "Blue Mana",
    ID_MANA_BLACK: "Black Mana",
    ID_MANA_RED: "Red Mana",
    ID_MANA_WHITE: "White Mana",
    ID_MANA_COLORLESS: "Colorless Mana",
    ID_MANA_GENERIC: "Generic Mana",

    ID_CARD_FOREST: "Forest",
    ID_CARD_ISLAND: "Island",
    ID_CARD_MOUNTAIN: "Mountain",
    ID_CARD_SWAMP: "Swamp",
    ID_CARD_PLAINS: "Plains",
    ID_CARD_GRIZZLY_BEARS: "Grizzly Bears",
    ID_CARD_GIANT_STRENGTH: "Giant Strength",

    ID_ABILITY_HASTE: "Haste",
    ID_ABILITY_TRAMPLE: "Trample",
    ID_ABILITY_FLYING: "Flying",
    ID_ABILITY_FIRST_STRIKE: "First Strike",
    ID_ABILITY_DEATHTOUCH: "Deathtouch",
    ID_ABILITY_LIFELINK: "Lifelink",
    ID_ABILITY_PROTECTION: "Protection",
    ID_ABILITY_DOUBLE_STRIKE: "Double Strike",
    ID_ABILITY_VIGILANCE: "Vigilance",
    ID_ABILITY_INDESTRUCTIBLE: "Indestructible",
    ID_ABILITY_FLASH: "Flash",
    ID_ABILITY_HEXPROOF: "Hexproof",
    ID_ABILITY_PROWESS: "Prowess",
    ID_ABILITY_MENACE: "Menace",
    ID_ABILITY_DEFENDER: "Defender",
    ID_ABILITY_REACH: "Reach",
    ID_ABILITY_TAP_ADD_GREEN: "Tap: Add Green Mana",
    ID_ABILITY_TAP_ADD_BLUE: "Tap: Add Blue Mana",
    ID_ABILITY_TAP_ADD_BLACK: "Tap: Add Black Mana",
    ID_ABILITY_TAP_ADD_RED: "Tap: Add Red Mana",
    ID_ABILITY_TAP_ADD_WHITE: "Tap: Add White Mana",
}

ID_TO_NAME = {
    ID_PLAYER: "Player",
    ID_CREATURE: "Creature",
    ID_ACTION_PLAY_LAND: "Play Land Action",
    ID_ACTION_TAP_FOR_MANA: "Tap for Mana Action",
    ID_ACTION_CAST_SPELL: "Cast Spell Action",
    ID_ACTION_PASS_TURN: "Pass Turn Action",

    ID_PHASE_BEGINNING: "Beginning Phase",
    ID_PHASE_MAIN1: "Pre-Combat Main Phase",
    ID_PHASE_COMBAT: "Combat Phase",
    ID_PHASE_MAIN2: "Post-Combat Main Phase",
    ID_PHASE_ENDING: "Ending Phase",

    ID_STEP_UNTAP: "Untap Step",
    ID_STEP_UPKEEP: "Upkeep Step",
    ID_STEP_DRAW: "Draw Step",
    ID_STEP_PRE_COMBAT_MAIN: "Pre-Combat Main Step",
    ID_STEP_BEGINNING_OF_COMBAT: "Beginning of Combat Step",
    ID_STEP_DECLARE_ATTACKERS: "Declare Attackers Step",
    ID_STEP_DECLARE_BLOCKERS: "Declare Blockers Step",
    ID_STEP_COMBAT_DAMAGE: "Combat Damage Step",
    ID_STEP_END_OF_COMBAT: "End of Combat Step",
    ID_STEP_POST_COMBAT_MAIN: "Post-Combat Main Step",
    ID_STEP_END: "End Step",
    ID_STEP_CLEANUP: "Cleanup Step",

    ID_ZONE_HAND: "Hand",
    ID_ZONE_BATTLEFIELD: "Battlefield",
    ID_ZONE_LIBRARY: "Library",
    ID_ZONE_GRAVEYARD: "Graveyard",
    ID_ZONE_STACK: "Stack",
    ID_ZONE_EXILE: "Exile",

    ID_REL_CONTROLS: "Controls",
    ID_REL_IS_IN_ZONE: "Is In Zone",
    ID_REL_HAS_ABILITY: "Has Ability",
    ID_REL_TAPPED: "Tapped",
    ID_REL_IS_BLOCKING: "Is Blocking",

    ID_MANA_GREEN: "Green Mana",
    ID_MANA_BLUE: "Blue Mana",
    ID_MANA_BLACK: "Black Mana",
    ID_MANA_RED: "Red Mana",
    ID_MANA_WHITE: "White Mana",
    ID_MANA_COLORLESS: "Colorless Mana",
    ID_MANA_GENERIC: "Generic Mana",

    ID_CARD_FOREST: "Forest",
    ID_CARD_ISLAND: "Island",
    ID_CARD_MOUNTAIN: "Mountain",
    ID_CARD_SWAMP: "Swamp",
    ID_CARD_PLAINS: "Plains",
    ID_CARD_GRIZZLY_BEARS: "Grizzly Bears",
    ID_CARD_GIANT_STRENGTH: "Giant Strength",

    ID_ABILITY_HASTE: "Haste",
    ID_ABILITY_TRAMPLE: "Trample",
    ID_ABILITY_FLYING: "Flying",
    ID_ABILITY_FIRST_STRIKE: "First Strike",
    ID_ABILITY_DEATHTOUCH: "Deathtouch",
    ID_ABILITY_LIFELINK: "Lifelink",
    ID_ABILITY_PROTECTION: "Protection",
    ID_ABILITY_DOUBLE_STRIKE: "Double Strike",
    ID_ABILITY_VIGILANCE: "Vigilance",
    ID_ABILITY_INDESTRUCTIBLE: "Indestructible",
    ID_ABILITY_FLASH: "Flash",
    ID_ABILITY_HEXPROOF: "Hexproof",
    ID_ABILITY_PROWESS: "Prowess",
    ID_ABILITY_MENACE: "Menace",
    ID_ABILITY_DEFENDER: "Defender",
    ID_ABILITY_REACH: "Reach",
    ID_ABILITY_TAP_ADD_GREEN: "Tap: Add Green Mana",
    ID_ABILITY_TAP_ADD_BLUE: "Tap: Add Blue Mana",
    ID_ABILITY_TAP_ADD_BLACK: "Tap: Add Black Mana",
    ID_ABILITY_TAP_ADD_RED: "Tap: Add Red Mana",
    ID_ABILITY_TAP_ADD_WHITE: "Tap: Add White Mana",
}
